export const PERMISSIONS = {
  "system:configure": "Manage system configuration",
  "audit:read": "View audit logs",
  "users:create": "Create users",
  "users:read": "View user list",
  "users:update": "Edit user profiles",
  "users:deactivate": "Deactivate/reactivate users",
  "patients:read": "View patient records",
  "patients:read_own": "View own patient record",
  "patients:create": "Register new patients",
  "patients:update": "Edit patient records",
  "patients:update_own": "Edit own profile",
  "vitals:create": "Record vitals",
  "vitals:read": "View patient vitals",
  "diagnoses:manage": "Manage diagnoses",
  "notes:create": "Create clinical notes",
  "notes:sign": "Sign clinical notes",
  "documents:upload": "Upload documents",
  "documents:read": "View documents",
  "appointments:create": "Book appointments",
  "appointments:create_own": "Book own appointments",
  "appointments:read": "View all appointments",
  "appointments:read_own": "View own appointments",
  "appointments:manage": "Manage appointments",
  "schedule:manage": "Manage provider availability",
  "video:conduct": "Conduct video visits",
  "video:join": "Join video visits",
  "messages:send": "Send messages",
  "messages:read": "Read messages",
  "messages:broadcast": "Send broadcast messages",
  "careplans:create": "Create care plans",
  "careplans:manage": "Manage care plan activities",
  "careplans:read_own": "View own care plans",
  "referrals:manage": "Manage referrals",
  "prescriptions:create": "Create prescriptions",
  "prescriptions:read_own": "View own prescriptions",
  "refills:request": "Request prescription refills",
  "refills:manage": "Manage refill requests",
  "labs:order": "Create lab orders",
  "labs:enter_results": "Enter lab results",
  "labs:review": "Review lab results",
  "labs:read_own": "View own lab results",
  "lab_catalog:manage": "Manage lab test catalog",
  "billing_codes:manage": "Manage billing codes",
  "invoices:create": "Create invoices",
  "invoices:read_own": "View own invoices",
  "claims:manage": "Manage claims",
  "payments:process": "Process payments",
  "payments:make": "Make payments",
  "insurance:verify": "Verify insurance",
  "insurance:manage_own": "Manage own insurance information",
  "payer_catalog:manage": "Manage insurance payers",
  "consent_templates:manage": "Manage consent templates",
  "consent:sign": "Sign consent forms",
  "consent:read": "Read consent records",
  "workflows:manage": "Manage workflow templates",
  "workflows:assign": "Assign workflows",
  "analytics:view": "View analytics dashboards",
  "analytics:view_own": "View own analytics",
  "settings:manage_own": "Manage own settings",
} as const

export type Permission = keyof typeof PERMISSIONS
